# Generated by Django 5.2 on 2026-09-07 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("research", "Research"),
                            ("volunteer", "Volunteer"),
                            ("part-time", "Part-Time"),
                            ("full-time", "Full-Time"),
                            ("freelance", "Freelance"),
                            ("competition", "Competition"),
                            ("organization", "Organization"),
                            ("committee", "Committee"),
                            ("community", "Community"),
                        ],
                        max_length=20,
                    ),
                ),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
