# Generated by Django 5.2 on 2026-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="experience_type",
            new_name="category",
        ),
    ]
