# Generated by Django 5.2 on 2026-09-08 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_experience_type_experience_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("project_url", models.URLField(blank=True, null=True)),
                ("technologies", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("mobile-app", "Mobile App"),
                            ("ai", "AI"),
                            ("contribution", "Contribution"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
