# Generated by Django 5.2 on 2026-09-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
