# Generated by Django 5.2 on 2026-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
